---
- name: open ports in items section
  firewalld:
   permanent: yes
   immediate: yes
   state: enabled
   port: "{{item}}"
    
  with_items:
      - '6443/tcp'
      - '2379/tcp'
      - '2380/tcp'
      - '10250-10252/tcp'
      - '10255/tcp'

- name: config Kubeadm
  command: kubeadm config images pull

- name: allow access from workers
  firewalld:
    rich_rule: "{{item}}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items:

     - 'rule family=ipv4 source address=10.0.1.12/32 accept'
     - 'rule family=ipv4 source address=10.0.1.13/32 accept'
      
- name: Permitimos acceso de los contenedores a localhost
  firewalld:
    rich_rule: "{{item}}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items:

     - 'rule family=ipv4 source address=172.17.0.0/16 accept'

- name: install CNI
  command: kubeadm init --pod-network-cidr 192.169.0.0/16

- name: generate token
  command: kubeadm token create --print-join-command
  register: join_token

- name: copy token
  local_action: copy content="{{ join_token.stdout_lines[0] }}" dest="./join-token"
  become: no  

- name: allow root access
  command: "{{ item }}"
  with_items:
   - mkdir -p /root/.kube
   - cp -i /etc/kubernetes/admin.conf /root/.kube/config
   - chown root:root /root/.kube/config