
  - name: conf kudeadm
    command: kubeadm config images pull


  - name: allow Access from Workers
    firewalld:
      rich_rule: "{{ item }}"
      permanent: yes
      state: enabled
      immediate: yes
    with_items:
      - "rule family=ipv4 source address={{ privada_worker01 }}/24 accept"
      - "rule family=ipv4 source address={{ privada_worker02 }}/24 accept"


  - name: install CNI 
    command: kubeadm init --pod-network-cidr 192.169.0.0/16 | tail -2 --ignore-preflight-errors=NumCPU
    register: kudeadm_init
  

  - name: cat kudeadm init
    set_fact: kudeadm_init="{{ kudeadm_init.stdout }}"


  - name: kube Directory
    file: 
      path: /root/.kube
      state: directory


  - name: change rute admin.conf
    copy:
      remote_src: yes
      src: /etc/kubernetes/admin.conf
      dest: /root/.kube/config


  - name: allow root
    file:
      path: /root/.kube/config
      owner: "{{ ansible_effective_user_id |string }}"
      group: "{{ ansible_effective_group_id |string }}"