- name: kubeadm conf
  command: kubeadm config images pull

- name: access to worker1
  firewalld:
    rich_rule: rule family=ipv4 source address=10.0.1.12/32 accept
    permanent: yes
    state: enabled

- name: access to Worker02
  firewalld:
    rich_rule: rule family=ipv4 source address=10.0.1.13/32 accept
    permanent: yes
    state: enabled

- name: reload firewall
  command: firewall-cmd --reload
  become: yes

- name: allow acces to localhost
  firewalld:
    rich_rule: rule family=ipv4 source address=172.17.0.0/16 accept
    zone: public
    permanent: yes
    state: enabled

- name: reload firewall
  command: firewall-cmd --reload
  become: yes

- name: CNI
  command: kubeadm init --pod-network-cidr 192.169.0.0/16
  register: kubeadm_init
  become: yes

- name: create /root/.kube
  command: mkdir -p /root/.kube
  become: yes

- name: allow access root
  command: cp /etc/kubernetes/admin.conf /root/.kube/config
  become: yes

- name: change permission admin.conf
  file: 
    path: /root/.kube/config
    owner: root
    group: root
  become: yes