---
- name: Hosts(1/1) - Configuration DNS Servers
    blockinfile: 
      path: /etc/hosts 
      state: present
      block: |
        {{ nfs_ip }}  nfs
        {{ masterc_ip }}  master
        {{ worker01_ip }}  worker01 
        {{ worker02_ip }}  worker02
      insertafter: EOF
   become: yes