---
- name: activate transparent masquerading
  command: modprobe br_netfilter

- name: open firewall port to masquerade 
  firewalld:
    masquerade: yes
    permanent: true
    state: enabled

- name:reload firewall
  command: firewall-cmd --reload
  become: yes

- name: allow Kubernetes traffic management
    dest: "/etc/sysctl.d/k8s.conf"
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
  become: yes

- name: apply /etc/sysctl.d/k8s.conf
  command: sysctl --system