---

  - name: modprobe module
    modprobe:
      name: br_netfilter
      state: present

  - name: enabled firewall
    firewalld:
      masquerade: "yes"
      state: enabled
      permanent: yes
      immediate: yes

  - name: allow traffic for kubernetes create file
    file:
      path: /etc/sysctl.d/k8s.conf
      state: touch

  - name: allow traffic for kubernetes writing file
    blockinfile:
      path: /etc/sysctl.d/k8s.conf
      state: present
      block: |
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1
      insertafter: EOF
      marker: "## {mark} net.bridge"


  - name: apply changes
    shell: sysctl --system