---

#MODIFY HOST 

- name:  /etc/hosts
  copy:
    dest: "/etc/hosts"
    content: |
      127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4
      ::1 localhost localhost.localdomain localhost6 localhost6.localdomain6 
	10.0.1.10 master master.acme.es 
	10.0.1.13 worker01 worker01.acme.es
	10.0.1.12 worker02 worker02.acme.es5
	10.0.1.11 nfs nfs.acme.es      
  become: yes





#MODIFY FIREWALL
- name: activate transparent masquerading
  command: modprobe br_netfilter

- name: open firewall port to masquerade 
  firewalld:
    masquerade: yes
    permanent: true
    state: enabled

- name:reload firewall
  command: firewall-cmd --reload
  become: yes

- name: allow Kubernetes traffic management
    dest: "/etc/sysctl.d/k8s.conf"
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
  become: yes

- name: apply /etc/sysctl.d/k8s.conf
  command: sysctl --system




#DISABLE SWAP
- name: disable swap
    shell: swapoff -a
    when: ansible_swaptotal_mb > 0


- name: modify /etc/fstab/
    lineinfile:
      path: /etc/fstab
      regexp: '/swap/d'
      line: ''



#INSTALL DOCKER

- name: add docker repo
  command: "/usr/bin/dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo"
  become: yes

- name: install docker-ce
  dnf:
    name: "docker-ce-20.10.6-3.el8"
    state: present
  become: yes

- name: start docker
  systemd:
    name: docker
    state: started
    enabled: yes
    masked: no
  become: yes



#INSTALL KUBERNETES

- name: kubernetes
  copy:
    dest: "/etc/yum.repos.d/kubernetes.repo"
    content: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      exclude=kubelet kubeadm kubectl
  become: yes


- name: Kubelet
  dnf:
    name: "kubelet"
    state: present
    disable_excludes: "kubernetes"
  become: yes


- name: Kubeadm
  dnf:
    name: "kubeadm"
    state: present
    disable_excludes: "kubernetes"
  become: yes


- name: kubectl
  dnf:
    name: "kubectl"
    state: present
    disable_excludes: "kubernetes"
  become: yes


- name: start kubelet
  systemd:
    name: kubelet
    state: started
    enabled: yes
    masked: no
  become: yes